var login = new Object();
login.lang = "Language"
login.user = " Username "
login.pass = " Password "
login.btnsub = "Submit"
login.logerr = "Username or Password Error!"
login.logtimeout = "Timeout!"
login.passempty = "Please enter password!"
login.userformat = "Cannot accept space character in user name."
login.passformat = "Cannot accept space character in password. "


var share = new Object();
share.changemsg1="Do not turn off or reboot the Device during this time"
share.changeok="Change setting successfully!"
share.fw="Firmware"
share.bt="Build Time"
share.md="Mode"
share.yes="Yes"
share.no="No"
share.refresh="Refresh";
share.help=" Help "
share.apply="Apply"
share.backup="Backup"
share.reset="Reset"
share.usrname="User Name"
share.passwd="Password"
share.hostname="Host Name"
share.domainname="Domain Name"
share.srv="Service Name"
share.unmask="Unmask"
share.manual="Manual"
share.auto="Auto"
share.server="Server"
share.client="Client"
share.enable="Enable";
share.enabled="Enabled";
share.disable="Disable";
share.disabled="Disabled";
share.add="Add";
share.del="Delete";
share.delsel="Delete Selected"
share.delall="Delete All"
share.selall="Select ALL"
share.cleall="Clear ALL"
share.close="Close";
share.next="Next";
share.back="Back";
share.save="Save&Reboot";
share.reboot="Reboot";
share.select="Select";
share.ssid="SSID";
share.bssid="Mac";
share.channel="Channel";
share.encrypt="Encrypt"
share.signal="Signal"
share.rssi="Rssi";
share.openn="Open";
share.rate="Rate";
share.key="Key";
share.day="Day";
share.from="From"
share.to="To"
share.hour="Hr";
share.minutes="Minu";
share.macaddr="MAC Address";
share.comment="Comment";
share.etime="Release Time";
share.packets="Packets";
share.errors="Errors"
share.mode="Mode";
share.pwsv="Power Saving"
share.rbnow="Reboot Now"
share.rblater="Reboot Later"
share.wait="Please wait"
share.seconds="seconds"
share.changeokMsg="Your changes have been saved. The router must be rebooted for the changes to take effect.<br> You can reboot now, or you can continue to make other changes and reboot later.\n"
share.reloadMsg="Do not turn off or reboot the Device during this time"
share.reloadok="Load Default successful?"
share.reloadMsg=" please don't turn off or restart During this time"
share.light="Light"
share.dark="Dark"
share.home="Home Page"
share.advset="Advance"
share.cancel="Cancel"
share.logout="logout"
share.con="Connect"
share.discon="Disconnect"
share.coned="Connected"
share.scanning="Scanning"
share.wfkey="Waiting for key"
share.stared="Start"
share.idle="Idle"
share.disabled="Disabled"
share.inclient="Infrastructure Client"
share.adclient="Ad-hoc Client"
share.hidden="Style"
share.color="Here you can switch the theme color"
share.coto="Connect to"

var inet = new Object();
inet.h2="WAN"
inet.wan_leg="WAN Basic Setting"
inet.lanh2="LAN Set"
inet.legend1="WAN connection type"
inet.legend3="DNS Set"
inet.advh2="advanced Setting"
inet.wan_con_type="Connection Type"
inet.static_ip="Static IP"
inet.auto_ip="Automatic Configuration - DHCP"
inet.pppoe="PPPOE";
inet.pppoe_connect_NO="PPPOE Connecting No"
inet.wan_ip="IP Address"
inet.wan_mask="Subnet Mask"
inet.wan_gateway="Default Gateway"
inet.wan_mtu="MTU Size"
inet.wan_type="WAN Access Type"
inet.wan_user="User Name"
inet.wan_pwd="Password"
inet.wan_ac="Service Name"
inet.wan_con_type="Connection Type"
inet.wan_con_con="Continuous"
inet.wan_con_demand="Connect on Demand"
inet.wan_con_manual="Manual"
inet.wan_idle="Idle Time"
inet.wan_subnet="Sub Net"
inet.wan_dynamic="Dynamic IP"
inet.wan_showadv="Show Advance Setting"
inet.wan_static="Static IP"
inet.wan_dial_num="Dial Number"
inet.wan_dns_auto="Attain DNS Automatically"
inet.wan_dns_manual="Set DNS Manual"
inet.wan_mac_clone="Clone MAC Address"
inet.wan_server_ip="Server IP Address"
inet.wan_dhcp_host="Host Name"
inet.lan_h2="LAN";
inet.lan_leg="LAN Setting"
inet.lan_dhcp_ran="DHCP Client Range"
inet.lan_lease="DHCP Lease Time"
inet.lan_802="802.1d Spanning Tree"
inet.dhcp_l="Lease time";
inet.dhcp_svr="DHCP Server";
inet.dhcp_cli="DHCP Client";
inet.clien_time="Time Expired(s)"
inet.client_h2="DHCP Client Table"
inet.client_legend="DHCP Client Table"
inet.static_msg2="Do you really want to delete the selected static IP entry?";
inet.static_msg3="Do you really want to delete the all static IP entry?";
inet.static_h2="Static DHCP"
inet.lan_set_static="Set Static DHCP"
inet.static_legend="Static DHCP Setup"
inet.static_legend1="Static DHCP List"
inet.static_dip="Destination IP Address"
inet.static_alert1="Invalid IP address value!"
inet.adv_upnp="UPnP";
inet.adv_igmp="IGMP Proxy";
inet.adv_ipsec="IPSec pass through on VPN connection";
inet.adv_pptp="PPTP pass through on VPN connection";
inet.adv_l2tp="L2TP pass through on VPN connection";
inet.adv_ipv6="IPv6 pass through on VPN connection";
inet.adv_ping="Ping Access on WAN"
inet.adv_web="Web Server Access on WAN"
inet.showclient="Show Client"
inet.pptp_msg1="PPTP user name cannot be empty!"
inet.pptp_msg2="PPTP password cannot be empty!"
inet.L2TP_msg1="L2TP user name cannot be empty!"
inet.L2TP_msg2="L2TP password cannot be empty!"
inet.ppp_msg1="PPP user name cannot be empty!"
inet.ppp_msg2="PPP password cannot be empty!"
inet.pptp_msg3="Invalid pptp default gateway IP address!\nIt should be located in the same subnet of local IP address."
inet.fixedIP="Fixed IP"

inet.adv_h2="Network Advance Setting"
inet.adv_leg="Advance Setting"
inet.adv_mac="Mac Clone"
inet.Mac_alert="eg:001122334455.type 000000000000 means disable cloning"

inet.alert1="Invalid default gateway address"
inet.alert2="Invalid gateway address!\nIt should be located in the same subnet of current IP address."
inet.alert3="Invalid MTU size! You should set a value between 1400-1500."
inet.alert4="Invalid MTU size! You should set a value between 1400-1492."
inet.alert5="Invalid idle time value! You should set a value between 1-1000."
inet.alert6="Invalid MTU size! You should set a value between 1360-1492."
inet.alert7="Invalid ip input"

var ddns = new Object();
ddns.h2="Dynamic Domain Name System (DDNS)";
ddns.legend="DDNS";
ddns.enable="Enable DDNS"
ddns.srv="DDNS Service";
ddns.name="User Name/Email"
ddns.pass="Password/Key"
ddns.alert1="Domain Name can't be empty"
ddns.alert2="User Name/Email can't be empty";
ddns.alert3="Password/Key can't be empty";

var wlan = new Object();
wlan.bs_h2="Wireless Basic Settings";
wlan.bs_legend="Wireless Basic Settings";
wlan.bs_onoff="Disable Wireless LAN Interface";
wlan.bs_band="Band";
wlan.bs_type="Network Type"
wlan.bs_infr="Infrastructure"
wlan.bs_ad="Ad hoc"
wlan.bs_mode="Wireless Mode";
wlan.bs_ssid="SSID";
wlan.bs_repssid="Wireless Repeater SSID"
wlan.bs_chan="Channel";
wlan.bs_chanwidth="Channel Width";
wlan.bs_chancontrol="Control Sideband";
wlan.bs_broadcase="Broadcast SSID";
wlan.bs_wmm="WMM";
wlan.bs_data="Data Rate"
wlan.bs_assoccli="Associated Clients";
wlan.bs_showmac="Show Active Clients";
wlan.bs_mactable="Active Wireless Client Table";
wlan.bs_map="Expand Wireless Network";
wlan.bs_vap="Virtual Wireless Network"
wlan.bs_wlext="Wireless Expansion Enable"
wlan.bs_repen="Wireless Repeater";
wlan.bs_macclone="Enable Mac Clone (Single Ethernet Client)"
wlan.bs_ssid2=	"Extend SSID"
wlan.bs_hidden="if turn off Broadcase SSID; WPS2.0 will be disabled"

wlan.ssid_msg="SSID cannot be empty";
wlan.bs_msg1="Scan timeout... \nNot found effective wireless network!";
wlan.map_access="Access";
wlan.map_acl="Active Client List"
wlan.se_h2="Wireless Security";
wlan.se_legend="Wireless network security settings";
wlan.se_mode="Security Mode";
wlan.se_person="Personal";
wlan.se_wpamixed="Mixed";
wlan.se_auth="Authentication"
wlan.se_keylen="Key Length"
wlan.se_keyfor="Key Format"
wlan.se_enter="Enterprise "
wlan.se_opsys="Open System"
wlan.se_sharekey="Shared Key"
wlan.se_shkey="Pre-Shared Key"
wlan.se_rsia="RADIUS Server IP Address"
wlan.se_rsp="RADIUS Server Port"
wlan.se_rspass="RADIUS Server Password"
wlan.se_cip="Cipher Suite"
wlan.se_alert1="This inside type is not supported.";
wlan.se_alert2="This EAP type is not supported."
wlan.se_alert3="Please make sure that wapi certs from remote AS have already been installed at webpae [WAPI] -> [Certificate Install]."
wlan.se_alert4="Please make sure that wapi certs from local AS have already been installed at webpae [WAPI] -> [Certificate Install]."
wlan.se_alert5="Wrong wapi cert selected index."
wlan.se_alert6="802.1x eap type not supported here!";
wlan.se_alert7="802.1x eap inside type not supported here!";
wlan.se_alert8="the wapi key should be at least 8 characters and no more than 32 characters";
wlan.se_alert9="The Hex Mode WAPI key length should be 64 Hex number";
wlan.se_alert10="Invalid key value. It should be in hex number (0-9 or a-f)."
wlan.se_alert11="WPA Cipher Suite Can't be empty."
wlan.se_alert12="WPA2 Cipher Suite Can't be empty."
wlan.se_alert13="WPA Cipher Suite Can't be empty."
wlan.se_alert14="WPA2 Cipher Suite Can't be empty.";
wlan.se_alert15="if TKIP only ; WPS2.0 will be disabled"
wlan.se_alert16="under WPA only or TKIP only,WPS2 daemon will be disabled";
wlan.se_alert17="WEP Key error!\nMust be 5/13 bits (0~9/a~z) or 10/26 bits (0~9/a~f).";
wlan.se_alert18="WPA Key Must be 8~63 bits,or 64 bits(Hex)"
wlan.se_dis="Disabled"
wlan.se_wpa="WPA"
wlan.se_wpa2="WPA2"
wlan.se_wpaMix="WPA Mixed"
wlan.wep64="WEP 64bits"
wlan.wep128="WEP 128bits"
	
wlan.ac_h2="Wireless Access Control";
wlan.ac_h="Prevent or only allowed to set the wireless terminal (MAC) to connect to a wireless router.";
wlan.ac_legend="Wireless Access Control Settings";
wlan.ac_type="Access Control Mode";
wlan.ac_mode1="Allow Listed";
wlan.ac_mode2="Deny Listed";
wlan.ac_mode1lst="Allow List:";
wlan.ac_mode2lst="Deny List:";
wlan.ac_msg1="Please select access control mode!";
wlan.ac_msg2="Do you really want to delete the selected access control entry?";
wlan.ac_msg3="Delete the all entries will cause all client cannot connect to AP.  Sure?";
wlan.ac_msg4="Input MAC address is not complete. It should be 12 digits in hex"
wlan.ac_msg5="Invalid MAC address. It should be in hex number (0-9 or a-f)."
wlan.ac_msg6="Do you really want to delete the all entries?"
wlan.ac_alert1="if ACL allow list turn on ; WPS2.0 will be disabled!"

wlan.adv_h2="Wireless Advanced Settings";
wlan.adv_legend="Advanced Settings";
wlan.adv_fragment="Fragment Threshold";
wlan.adv_rts="RTS Threshold";
wlan.adv_beacon="Beacon Interval";
wlan.adv_preamble="Preamble Type";
wlan.adv_long="Long Preamble";
wlan.adv_short="Short Preamble";
wlan.adv_iapp="IAPP"
wlan.adv_protection="Protection";
wlan.adv_aggregation="Aggregation";
wlan.adv_shortgi="Short GI";
wlan.adv_partition="WLAN Partition";
wlan.adv_stbc="STBC";
wlan.adv_txb="TX Beamforming"
wlan.adv_conexist="20/40MHz Coexist"
wlan.adv_power="RF Output Power";
wlan.adv_alert1="Invalid value of Fragment Threshold. Input value should be between 256-2346 in decimal"
wlan.adv_alert2="Invalid value of RTS Threshold. Input value should be between 0-2347 in decimal"
wlan.adv_alert3="Invalid value of Beacon Interval. Input value should be between 20-1024 in decimal"
wlan.adv_alert4="Invalid value. It should be in decimal number (0-9)."

wlan.sch_h2="Wireless Schedule"
wlan.sch_legend="Schedule"
wlan.sch_en="Enable Wireless Schedule"
wlan.sch_wd7="Sun"
wlan.sch_wd1="Mon"
wlan.sch_wd2="Thu"
wlan.sch_wd3="Wed"
wlan.sch_wd4="Tue"
wlan.sch_wd5="Fri"
wlan.sch_wd6="Sat"
wlan.sch_wde="Everyday"

wlan.wds_h2="WDS";
wlan.wds_h2_1="WDS Settings -wlan"
wlan.wds_legend="WDS Settings";
wlan.wds_setsec="Security Setting"
wlan.wds_sec="Encryption"
wlan.wds_keyfor="WEP Key Format"
wlan.wds_show="Show Statistics"
wlan.wds_enable="Enable WDS"
wlan.wds_wepkey="WEP Key"
wlan.wds_pkeyfor="Pre-Shared Key Format"
wlan.wds_list="Current WDS AP List"
wlan.wds_error="Currently wireless mode do not support WDS wireless connection, your must switch to AP+WDS mode or WDS mode!";
wlan.wdstb_h2="WDS AP Table"

wlan.wps_h2="Wi-Fi Protected Setup";
wlan.wps_legend="Wi-Fi Protected Setup";
wlan.wps_legend2="WPS status"
wlan.wps_unconf="UnConfigured";
wlan.wps_conf="Configured";
wlan.wps_reset="Reset to UnConfigured";
wlan.wps_type="WPS Mode";
wlan.wps_pbc="PBC";
wlan.wps_pin="PIN";
wlan.wps_starpin="Start PIN"
wlan.wps_starpbc="Start PBC"
wlan.wps_stopwcs="STOP WSC"
wlan.wps_sepin="Self-PIN Number"
wlan.wps_clipin="Client PIN Number";
wlan.wps_pinconf="PIN Configuration"
wlan.wps_amor="Assign Mac of Registrar"
wlan.wps_asor="Assign SSID of Registrar"
wlan.wps_push="Push Button Configuration"
wlan.wps_msg1="Invalid Enrollee PIN length! \nPlease enter 4 or 8 bits PIN number.";
wlan.wps_msg2="Invalid Enrollee PIN! \nEnrollee PIN must be numeric digits.";
wlan.wps_msg3="Checksum failed! Use PIN anyway? ";
wlan.wps_alds="Auto-lock-down state"
wlan.wps_unlock="Unlock"
wlan.wps_locked="locked"
wlan.wps_unlocked="unlocked"
wlan.wps_s0="WPS Protocol Started";
wlan.wps_s1="Overlapping while PBC";
wlan.wps_s2="WPS Protocol Time-out";
wlan.wps_s3="Success";
wlan.wps_s4="EAPOL_START Sent";
wlan.wps_s5="Received EAPOL-start packet";
wlan.wps_s6="Received EAPOL-request for identity";
wlan.wps_s7="Received EAPOL-response for identity";
wlan.wps_s8="WSC-start Sent";
wlan.wps_s9="M1 Sent";
wlan.wps_s10="M1 Received";
wlan.wps_s11="M2 Sent";
wlan.wps_s12="M2 Received";
wlan.wps_s13="M2D Received";
wlan.wps_s14="M3 Sent";
wlan.wps_s15="M3 Received";
wlan.wps_s16="M4 Sent";
wlan.wps_s17="M4 Received";
wlan.wps_s18="M5 Sent";
wlan.wps_s19="M5 Received";
wlan.wps_s20="M6 Sent";
wlan.wps_s21="M6 Received";
wlan.wps_s22="M7 Sent";
wlan.wps_s23="M7 Received";
wlan.wps_s24="M8 Sent";
wlan.wps_s25="M8 Received";
wlan.wps_s26="Process EAP ACK";
wlan.wps_s27="Process EAP WSC-FAIL";
wlan.wps_s28="HASH Failed";
wlan.wps_s29="HMAC Failed";
wlan.wps_s30="Authentication Failed";
wlan.wps_s31="Invalid PIN code";
wlan.wps_s32="Process EAP-done packet";
wlan.wps_help1="You can choose PBC or PIN connection. If there are any problems in connecting, you can press <em>Reset to UnConfigured</em> button to clear the configuration and then try to connect.";
wlan.wps_worn1="WPS was disabled automatically because wireless mode setting could not be supported. You need go to Wireless/Basic page to modify settings to enable WPS."
wlan.wps_worn2="WPS was disabled automatically because Radius Authentication could not be supported. You need go to Wireless/Security page to modify settings to enable WPS."
wlan.wps_cstate="Current state"	

var upgrade = new Object();
upgrade.h2="Firmware Upgrade"
upgrade.legend="Firmware Management"
upgrade.apply="Upgrade"
upgrade.alert2="File name can not be empty !"
upgrade.alert1="Update firmware failed!"
upgrade.selfile="Select File"
upgrade.save="Save..."
upgrade.upload="Upload"
upgrade.br="Browse"	


var backup = new Object();
backup.h2="Configuration"
backup.legend="Backup Settings"
backup.alert1="Do you really want to reset the current settings to default?"
backup.save="Save Settings to File"
backup.load="Load Settings from File"
backup.reset="Reset to Default Settings";
backup.mess2="please select a file!"

var tz = new Object();
tz.h2="Time Zone";
tz.legend="Time Zone Setting";
tz.curtime="Current Time"
tz.yr="Yr"
tz.mon="Mon"
tz.day="Day";
tz.hr="Hr"
tz.min="Mn"
tz.sec="Sec"
tz.pctime="Copy Computer Time";
tz.zone="Time Zone";
tz.ntp="Enable NTP client update";
tz.auto="Automatically Adjust Daylight Saving";
tz.svr="NTP server";
tz.na="North America";
tz.europe="Europe";
tz.australia="Australia";
tz.asia="Asia Pacific";
tz.manuip="Manual IP Setting";
tz.alert1="Invalid month Number."
tz.alert2="Invalid Time value!"
tz.alert3="Invalid IP address"
tz.alert4="Invalid NTP Server IP address! It can not be empty.";
tz.alert5="Invalid value. It should be in  number (0-9)."

var log = new Object();
log.h2 = "System Log";
log.legend="System Log";
log.ebable="Enable System log";
log.sysall="system all"
log.wire="wireless"
log.dos="DoS";
log.remote="Enable Remote Log";
log.srvip="Log Server IP Address"
log.alert1="Invalid Server address!"


var admin = new Object();
admin.h2="Router Management"
admin.legend="Router Password"
admin.login=	"Administration"
admin.psswd_user="Router Username"
admin.psswd_pass="New Password"
admin.pass_conf="Re-enter to confirm"
admin.upload= "Firmware&#10;Upgrade"

var statu = new Object();
statu.h2="Current Mode";
statu.ipPro="Attain IP Protocol";
statu.ipaddr="IP Address";
statu.sub="Subnet Mask";
statu.gtway="Default Gateway";
statu.mac="MAC Address"
statu.dhcp="DHCP Server"
statu.ass="Associated Clients"
statu.state="State"
statu.reint="Wireless Repeater Interface"
statu.vir="Virtual"
statu.router_legend="System"
statu.wlan_legend="Wireless Network"
statu.uptime="Uptime"
statu.chnum="Channel Number"
statu.fw="Firmware Version"
statu.bt="Build Time"
statu.lan_legend="Lan Status"
statu.wan_legend="Wan Status"

var home = new Object();
home.wel="Welcome";
home.opmode="Operation Mode";
home.contype="WAN Contype";
home.ap="AP";
home.router="Router";
home.repeater="Repeater";
home.bridge="Bridge";
home.wisp="Wireless&#10;ISP"
home.wispH2="Wireless ISP"
home.setok="Setting successful"
home.client="Client";
home.apt="Access Point mode";
home.routert="Wireless router mode";
home.repeatert="Repeater mode";
home.bridget="Bridge Mode";
home.clientt="Client Mode";
home.apc="In this mode ,the wired interface as the LAN port to user, the computer can connect to wired or wireless router. To avoid conflict and front-end network equipment DHCP, the DHCP server in this mode off by default, if you want to log into the router management page, you need to manually set the computer's IP address.";
home.routerc="In this mode, the wired interface as the WAN port to use, computers can only connect to the router via wireless. This mode, the DHCP server enabled by default, recommended that computer's IP address and DNS address set to automatically obtain.";
home.repeaterc="In this mode, the wired interface as the LAN port to use, the computer can connect to wired or wireless router. At this point the router's SSID to connect to the front of the relay router's SSID. To avoid conflict and front-end network equipment DHCP, the DHCP server in this mode off by default, if you want to log into the router management page, you need to manually set the computer's IP address.";
home.bridgec="In this mode, the wired interface as the LAN port to use, the computer can connect to wired or wireless router. To avoid conflict and front-end network equipment DHCP, the DHCP server in this mode off by default, if you want to log into the router management page, you need to manually set the computer's IP address.";
home.clientc="In this mode, the wired interface as the LAN port to use, computers can only connect to the router via cable. To avoid conflict and front-end network equipment DHCP, the DHCP server in this mode off by default, if you want to log into the router management page, you need to manually set the computer's IP address.";
home.wan0="WAN";
home.wan0t0="Internet service providers offer a fixed IP address (static IP)";
home.wan0t1="Automatically obtain an IP address (dynamic IP)";
home.wan0t2="ADSL Dial-up (PPPoE)";
home.alert1="Key error!\nMust be 8 ~ 63 bits and letters or 64 bits (0~9 a~f)";
home.alert2="Wireless expansion is disabled!"


var menu = new Object();
menu.bchome="Back home"
menu.wiz="Wizard"
menu.opmode="Mode"
menu.tcpip="Network";
menu.tcpipwan="WAN Settings";
menu.tcpiplan="LAN Settings";
menu.tcpipadv="Advanced"
menu.advance="Advanced";
menu.wireless="Wireless"
menu.wlbasic="Basic Settings"
menu.wlsecurity="Wireless Security"
menu.wirelessfilter="MAC Filter"
menu.wladvance="Advanced Settings"
menu.wlwds="WDS"
menu.wlwps="WPS"
menu.wlsch="Schedule"
menu.wladvanced="advanced"
menu.wlactrl="Access Control"
menu.firewall="Firewall";
menu.portfilter="Port Filtering";
menu.ipfilter="IP Filtering";
menu.macfilter="MAC Filtering";
menu.urlfilter="URL Filtering";
menu.portfw="Port Forwarding";
menu.dmz="DMZ";
menu.qos="QoS"
menu.tcpip_adv= "Advance Setting"
menu.advset="Advanced";
menu.ddns="Dynamic DNS";
menu.advsetrouting="Advanced Routing";
menu.vlan="VLANs";
menu.dos="DoS";
menu.admin="Management";
menu.saveconf="Backup&&#10;Reset";
menu.stats="Statistics"
menu.syslog="Log"
menu.tz="Time Zone"
menu.upgrade="Firmware Upgrade"
menu.adminBackup="Backup"
menu.adminreboot="Reboot";
menu.statu="Status"
menu.statuRouter="Router"
menu.statuInet="WAN"
menu.statuLAN="LAN"
menu.statuWLAN="Wireless"
menu.status="Status"

var f_port = new Object();
f_port.h2="Port Filtering";
f_port.h="Limit router port of use.";
f_port.legend="Port Filtering Setting";
f_port.enable="Enable Port Filtering";
f_port.range="Port Range";
f_port.both="Both"
f_port.ip="Local IP Address"
f_port.protol="Protocol";
f_port.table="Current Filter Table:";
f_port.msg1="Invalid port number! You should set a value between 1-65535.";
f_port.msg2="Invalid port range! 1st port value should be less than 2nd value.";
f_port.msg3="Do you really want to delete the selected port filter entry?";
f_port.msg4="Do you really want to delete the all port filter entries?";
f_port.alert1="You should set a port range for adding in an entry"

var f_pw = new Object();
f_pw.h2="Port Forwarding";
f_pw.legend="Port Forwarding Setting";
f_pw.enable="Enable Port Forwarding";
f_pw.ipaddr="IP Address"

var f_ip = new Object();
f_ip.h2="IP Filtering";
f_ip.h="Limit the IP address for TCP/UDP packets through the router.";
f_ip.legend="IP Filtering Setting";
f_ip.enable="Enable IP Filtering";
f_ip.range="IP Address";
f_ip.msg3="Do you really want to delete the selected ip filter entry?";
f_ip.msg4="Do you really want to delete the all ip filter entries?";

var f_mac = new Object();
f_mac.h2="MAC Filtering";
f_mac.h="Limit the MAC address to access the Internet through a router.";
f_mac.legend="MAC Filtering Setting";
f_mac.enable="Enable MAC Filtering";
f_mac.range="MAC Address";
f_mac.msg3="Do you really want to delete the selected MAC filter entry?";
f_mac.msg4="Do you really want to delete the all MAC filter entries?";

var f_url = new Object();
f_url.h2="URL Filtering";
f_url.h="Restrict PC access the site set.";
f_url.legend="URL Filtering Setting";
f_url.enable="Enable URL Filtering";
f_url.range="URL Address";
f_url.msg1="Error character';'";
f_url.msg3="Do you really want to delete the selected URL filter entry?";
f_url.msg4="Do you really want to delete the all URL filter entries?";

var f_dmz = new Object();
f_dmz.h2="DMZ";
f_dmz.legend="DMZ";
f_dmz.enable="Enable DMZ";
f_dmz.ipaddr="DMZ Host IP Address";
f_dmz.msg1="Please enter ip address!";
f_dmz.msg2="DMZ Host IP address and local IP is not in same network segment!";
f_dmz.help1="Enabling this option will expose the specified host to the Internet. All ports will be accessible from the Internet.";

var qos = new Object();
qos.h2="Quality of Service";
qos.legend="QoS Set";
qos.enable="Enable QoS";
qos.autoup="Automatic Uplink Speed"
qos.manup="Manual Uplink Speed";	
qos.autodo="Automatic Downlink Speed"
qos.mando="Manual Downlink Speed"
qos.rule="QoS Rule Setting"
qos.table="Current QoS Rules Table"
qos.legend2="QoS Rule";
qos.type="Address Type";
qos.typeip="IP Address";
qos.typemac="MAC Address";
qos.layer="Layer 7 Rule";
qos.mode="Mode";
qos.min="Guaranteed minimum bandwidth";
qos.max="Restricted maximum bandwidth";
qos.upbw="Uplink Bandwidth"
qos.dobw="Downlink Bandwidth";
qos.alert1="Manual Uplink Speed cannot be empty or less then 100 when Automatic Uplink Speed is disabled.";
qos.alert2="Manual Downlink Speed cannot be empty or less then 100 when Automatic Downlink Speed is disabled.";
qos.alert3="Invalid IP address range!\nEnding address should be greater than starting address.";
qos.alert4="Invalid start IP address! It should be set within the current subnet.";
qos.alert5="Input MAC address is not complete. It should be 12 digits in hex.";
qos.alert6="Invalid MAC address. It should be in hex number (0-9 or a-f).";
qos.alert7="Uplink Bandwidth or Downlink Bandwidth cannot be empty.";
qos.alert8="Invalid input! It should be the decimal number (0-9).";
qos.alert9="Do you really want to delete the selected QoS filter entry?";
qos.alert10="Do you really want to delete the all QoS filter entries?";

var vlans = new Object();
vlans.h2="VLAN";
vlans.legend="VLAN configuration";
vlans.enable="Enable VLAN";
vlans.interf="Interface";
vlans.inttype="Interface Type";
vlans.tag="Tag";
vlans.forrul="Forwarding<br>Rule"
vlans.vid="VID";
vlans.vidh="VLAN ID";
vlans.Priority="Priority";
vlans.cfi="CFI";
vlans.alert1="Invalid Vlan ID";

var dos = new Object();
dos.h2="Denial of Service";
dos.enable="Enable DoS";
dos.system="Whole System Flood";
dos.ipadd="Per-Source IP Flood";
dos.portscan="PortScan";
dos.low="Low";
dos.ps="Packets/Second";
dos.high="High";
dos.sen="Sensitivity"
dos.selall="Select All";
dos.clearall="Clear selection";
dos.sourip="Enable Source IP Blocking ";
dos.blocktime="Block time (sec)";
dos.help1="Prevent malicious attack";


var errmsg = new Object();
errmsg.msg1="Please enter the correct value"
errmsg.msg2="Please input!"

var pg_title = new Object();
pg_title.info = "Wireless Mini Router"
pg_title.logoff = "Logout"
